### ISSUE TITLE
Income Prediction Error sh job_runner.sh TrainModel

### ISSUE THREAD

**Issue by kentran267** [airbnb/aerosolve#252]
I got this error while trying to run `sh job_runner.sh TrainModel`

I ran it within the demo/income_prediction folder. 
Everything was built with Gradle successfully. 

`sh job_runner.sh MakeTraining` and `sh job_runner.sh MakeTesting` worked and did make outfile files

Running 
scala 2.11.8
spark 2.0.1

```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.rdd.RDD.coalesce$default$3(IZ)Lscala/math/Ordering;
	at com.airbnb.aerosolve.training.AdditiveModelTrainer$.sgdTrain(AdditiveModelTrainer.scala:416)
	at com.airbnb.aerosolve.training.AdditiveModelTrainer$.train(AdditiveModelTrainer.scala:262)
	at com.airbnb.aerosolve.training.AdditiveModelTrainer$.trainAndSaveToFileEarlySample(AdditiveModelTrainer.scala:786)
	at com.airbnb.aerosolve.training.AdditiveModelTrainer$.trainAndSaveToFile(AdditiveModelTrainer.scala:768)
	at com.airbnb.aerosolve.training.TrainingUtils$.trainAndSaveToFile(TrainingUtils.scala:192)
	at com.airbnb.aerosolve.demo.IncomePrediction.IncomePredictionPipeline$.trainModel(IncomePredictionPipeline.scala:93)
	at com.airbnb.aerosolve.demo.IncomePrediction.JobRunner$$anonfun$main$1.apply(JobRunner.scala:41)
	at com.airbnb.aerosolve.demo.IncomePrediction.JobRunner$$anonfun$main$1.apply(JobRunner.scala:32)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at com.airbnb.aerosolve.demo.IncomePrediction.JobRunner$.main(JobRunner.scala:32)
	at com.airbnb.aerosolve.demo.IncomePrediction.JobRunner.main(JobRunner.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:736)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala
```

**Comment by kentran267** [comment]
Issue fixed when run with Spark 1.6.2
